customhost = "database-1.ctqdzmxmliea.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "yeojunken-employee"
customregion = "us-east-1"
